version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: findit_db
      POSTGRES_USER: findit_user
      POSTGRES_PASSWORD: findit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - findit_network

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - findit_network

  # FastAPI Backend
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://findit_user:findit_password@postgres:5432/findit_db
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
      - embeddings_data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - findit_network

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - findit_network

  # Optional: Celery Worker for background tasks
  celery_worker:
    build: ./backend
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://findit_user:findit_password@postgres:5432/findit_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
      - embeddings_data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - findit_network

volumes:
  postgres_data:
  uploads_data:
  embeddings_data:

networks:
  findit_network:
    driver: bridge
